sudo: required
language: generic 
services:
  - docker

before_install:
  - docker build -t akshay/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true akshay/react-test npm test

after_success:
  - docker build -t akshay/multi-client ./client
  - docker build -t akshay/multi-nginx ./nginx
  - docker build -t akshay/multi-server ./server
  - docker build -t akshay/multi-worker ./worker

  #Log in to docker cli with one single command
  - echo "$Docker_password" | docker login -u "$Docker_ID" --password-stdin

  - docker push akshay/multi-client
  - docker push akshay/multi-nginx
  - docker push akshay/multi-server
  - docker push akshay/multi-worker