sudo: required
language: generic 
services:
  - docker

before_install:
  - docker build -t akshay/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true USERNAME/react-test npm test

after_success:
  - docker build -t akshay/multi-client ./client
  - docker build -t akshay/multi-nginx ./nginx
  - docker build -t akshay/multi-server ./server
  - docker build -t akshay/multi-worker ./worker